CREATE DATABASE IF NOT EXISTS sena;
USE sena;

CREATE TABLE clientes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    empresa VARCHAR(100),
    telefono VARCHAR(15),
    direccion VARCHAR(255)
);

CREATE TABLE categorias (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE productos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    estado BOOL,
    nombre VARCHAR(100) NOT NULL,
    categoria_id INT,
    precio_unitario DECIMAL(10, 2) NOT NULL,
    stock INT,
    FOREIGN KEY (categoria_id) REFERENCES categorias(id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE facturas (
    id INT PRIMARY KEY AUTO_INCREMENT,
    cliente_id INT,
    total DECIMAL(10, 2) NOT NULL,
    -- AQUI QUEDE, EN COMO TRATAR UN ATRIBUTO CALCULADO
    FECHA DATE NOT NULL,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE DETALLE_FACTURAS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FACTURA_ID INT,
    PRODUCTO_ID INT,
    CANTIDAD INT NOT NULL,
    FOREIGN KEY (FACTURA_ID) REFERENCES FACTURAS(ID),
    ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT INTO CLIENTES (NOMBRE, APELLIDO, EMPRESA, TELEFONO, DIRECCION) VALUES
('JUAN', 'PÉREZ', 'TECH SOLUTIONS', '555-1234', 'AV. LIBERTADOR 1234'),
('ANA', 'MARTÍNEZ', 'MARKETING SA', '555-5678', 'CALLE 9 DE JULIO 876'),
('LUIS', 'GÓMEZ', 'CONSTRUCCIONES GÓMEZ', '555-8765', 'CALLE CORRIENTES 2345');

INSERT INTO CATEGORIAS (NOMBRE) VALUES
('ELECTRÓNICA'),
('HERRAMIENTAS'),
('MOBILIARIO');

INSERT INTO PRODUCTOS (NOMBRE, CATEGORIA_ID, PRECIO_UNITARIO, STOCK) VALUES
('LAPTOP', 1, 1200.00, 50),
('TALADRO', 2, 150.00, 30),
('ESCRITORIO', 3, 225.00, 20),
('RATÓN', 1, 25.00, 100),
('TECLADO', 1, 45.00, 80);

INSERT INTO FACTURAS (CLIENTE_ID, TOTAL, FECHA) VALUES
(1, 1250.00, '2024-08-22'),
(2, 300.00, '2024-08-22'),
(3, 450.00, '2024-08-22');

INSERT INTO DETALLE_FACTURAS (FACTURA_ID, PRODUCTO_ID, CANTIDAD) VALUES
(1, 1, 1),
(1, 4, 2),
(1, 5, 1), 
(2, 2, 2),  
(3, 3, 2);   
